theme: jekyll-theme-cayman
show_downloads: "true"
github:
  zip_url: https://github.com/HercDotTech/package-jquery-snow/archive/v3.0.0.zip
  tar_url: https://github.com/HercDotTech/package-jquery-snow/archive/v3.0.0.tar.gz
